imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: da

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig', 'php']

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      sharing_host: %sharing_host%
      sharing_enabled: %sharing_enabled%
      search_host: %search_host%
      search_host_public: %search_host_public%
      search_index: %search_index%
      site_title: %site_title%
      version: %version%
      itk_log_version: %itk_log_version%
      itk_log_error_callback: %itk_log_error_callback%
      itk_log_log_to_console: %itk_log_log_to_console%
      itk_log_log_level: %itk_log_log_level%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%"
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Mailgun bundle
cspoo_swiftmailer_mailgun:
    key: "%mailgun_key%"
    domain: "%mailgun_domain%"
    endpoint: "%mailgun_endpoint%"

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  port:      "%mailer_port%"
  password:  "%mailer_password%"
  spool:     { type: memory }

# FOSUser Configuration
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Os2Display\CoreBundle\Entity\User
  from_email:
    address: '%mailer_from_email%'
    sender_name: '%mailer_from_name%'

sonata_core:
    form:
        mapping:
            enabled: false

# Sonata Media Configuration
sonata_media:
  default_context: default
  db_driver: doctrine_orm
  contexts:
    default:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file
      formats:
        landscape: { width: 960 }
        portrait: { height: 540 }
        landscape_small: { width: 300 }
        portrait_small: { height: 150 }
  cdn:
    server:
      path: '%absolute_path_to_server%/uploads/media'
  filesystem:
    local:
      directory:  '%kernel.root_dir%/../web/uploads/media'
      create:     false
  class:
    media: Os2Display\MediaBundle\Entity\Media
    gallery: Os2Display\MediaBundle\Entity\Gallery
    gallery_has_media: Os2Display\MediaBundle\Entity\GalleryHasMedia

# JMS Serializer Configuration
jms_serializer:
  metadata:
    auto_detection: true
    directories:
      SonataMediaBundle:
        namespace_prefix: "Sonata\\MediaBundle"
        path: "@Os2DisplayMediaBundle/Resources/config/serializer/SonataMedia"

fos_rest:
    routing_loader:
        default_format: json
        include_format: true
    param_fetcher_listener: force
    body_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
            # xml: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true } # Available for version >= 1.5

nelmio_api_doc: ~

os2_display_exchange:
    enabled: true
    host: "%os2display_exchange.host%"
    user: "%os2display_exchange.user%"
    password: "%os2display_exchange.password%"
    version: Exchange2010
    cache_ttl: 1800
